#!/usr/bin/env bash
# knowledge-map/scripts/gen_knowledge_map.sh
# Derive KNOWLEDGE_MAP.md from its sources and print it to STDOUT (deterministic).
#   --print-map-path : print the absolute path of the map file and exit.
# The pre-commit hook redirects this into KNOWLEDGE_MAP.md and stages it, so map-drift is
# structurally impossible. check_knowledge_map.sh diffs a fresh render against the committed
# file to catch any out-of-band edit (e.g. in CI, where the hook did not run).
set -uo pipefail
ROOT="$(git rev-parse --show-toplevel)"
MAP="$ROOT/KNOWLEDGE_MAP.md"
if [ "${1:-}" = "--print-map-path" ]; then echo "$MAP"; exit 0; fi
cd "$ROOT"

cat <<'HDR'
# KNOWLEDGE_MAP — derived orientation map

<!-- DERIVED — DO NOT EDIT. Regenerated by knowledge-map/scripts/gen_knowledge_map.sh and
     staged by the pre-commit hook, so drift is structurally impossible. Edit the SOURCES:
     knowledge-map/subsystems.md, docs/tasks/, docs/decisions/. -->

## Key subsystems
HDR
if [ -f knowledge-map/subsystems.md ]; then
  # embed the curated section, stripping its leading HTML comment block
  sed '/^<!--/,/-->/d' knowledge-map/subsystems.md
fi

echo
echo "## Active task-trees"
echo
found=0
for f in $(ls docs/tasks/*.md 2>/dev/null | LC_ALL=C sort); do
  b="$(basename "$f")"; [ "$b" = "TEMPLATE.md" ] && continue
  echo "- [\`$b\`](docs/tasks/$b)"; found=1
done
if [ "$found" = 0 ]; then echo "- _none yet_"; fi

echo
echo "## Decision records"
echo
found=0
for f in $(ls docs/decisions/*.md 2>/dev/null | LC_ALL=C sort); do
  b="$(basename "$f")"; case "$b" in INDEX.md|TEMPLATE.md) continue;; esac
  echo "- [\`$b\`](docs/decisions/$b)"; found=1
done
if [ "$found" = 0 ]; then echo "- _none yet_"; fi
