//! Independent closed kind matrix and actual normative-table agreement for operators.
#![allow(clippy::unwrap_used, clippy::expect_used)]
use sc_core::recipe::{FormulaBinaryOperator as B, FormulaKind as K, FormulaUnaryOperator as U};

const KINDS: [K; 8] = [
    K::Length,
    K::Angle,
    K::Area,
    K::Ratio,
    K::Count,
    K::Boolean,
    K::Point,
    K::Edge,
];
const ARITHMETIC: [K; 5] = [K::Length, K::Angle, K::Area, K::Ratio, K::Count];
const OPERATORS: [(B, &str); 10] = [
    (B::Add, "+"),
    (B::Subtract, "-"),
    (B::Multiply, "*"),
    (B::Divide, "/"),
    (B::Equal, "=="),
    (B::NotEqual, "!="),
    (B::Less, "<"),
    (B::LessEqual, "<="),
    (B::Greater, ">"),
    (B::GreaterEqual, ">="),
];
// These are the grammar5.1 rows, not an expansion generated by the implementation.
const PAIRS: [(K, K, Option<K>, K); 14] = [
    (K::Length, K::Length, Some(K::Area), K::Ratio),
    (K::Length, K::Ratio, Some(K::Length), K::Length),
    (K::Length, K::Count, Some(K::Length), K::Length),
    (K::Angle, K::Angle, None, K::Ratio),
    (K::Angle, K::Ratio, Some(K::Angle), K::Angle),
    (K::Angle, K::Count, Some(K::Angle), K::Angle),
    (K::Area, K::Length, None, K::Length),
    (K::Area, K::Ratio, Some(K::Area), K::Area),
    (K::Area, K::Count, Some(K::Area), K::Area),
    (K::Area, K::Area, None, K::Ratio),
    (K::Ratio, K::Ratio, Some(K::Ratio), K::Ratio),
    (K::Ratio, K::Count, Some(K::Ratio), K::Ratio),
    (K::Count, K::Count, Some(K::Count), K::Ratio),
    (K::Count, K::Ratio, Some(K::Ratio), K::Count),
];

#[test]
fn unary_population_and_canonical_tokens_are_exact() {
    assert_eq!(K::ALL, KINDS);
    assert_eq!(U::Negate.token(), "-");
    assert_eq!(U::Square.token(), "^2");
    for kind in KINDS {
        let negated = [K::Length, K::Angle, K::Area, K::Ratio]
            .contains(&kind)
            .then_some(kind);
        let square_rows = [
            (K::Length, K::Area),
            (K::Ratio, K::Ratio),
            (K::Count, K::Count),
        ];
        let squared = square_rows
            .iter()
            .find(|(input, _)| *input == kind)
            .map(|(_, result)| *result);
        assert_eq!(U::Negate.result_kind(kind), negated, "negation {kind:?}");
        assert_eq!(U::Square.result_kind(kind), squared, "square {kind:?}");
    }
}

#[test]
fn every_ordered_binary_pair_matches_independent_closed_rows_and_hint_population() {
    let mut accepted = 0;
    let mut products = 0;
    let mut quotients = 0;
    let mut hints = 0;
    for (operator, token) in OPERATORS {
        assert_eq!(operator.token(), token);
        for left in KINDS {
            for right in KINDS {
                let same_arithmetic = left == right && ARITHMETIC.contains(&left);
                let expected = match operator {
                    B::Add | B::Subtract => same_arithmetic.then_some(left),
                    B::Multiply => PAIRS
                        .iter()
                        .find(|(l, r, _, _)| {
                            (*l == left && *r == right) || (*l == right && *r == left)
                        })
                        .and_then(|(_, _, result, _)| *result),
                    B::Divide => PAIRS
                        .iter()
                        .find(|(l, r, _, _)| *l == left && *r == right)
                        .map(|(_, _, _, result)| *result),
                    B::Equal
                    | B::NotEqual
                    | B::Less
                    | B::LessEqual
                    | B::Greater
                    | B::GreaterEqual => same_arithmetic.then_some(K::Boolean),
                };
                let actual = operator.result_kind(left, right);
                assert_eq!(actual, expected, "{left:?} {token} {right:?}");
                let hint = operator == B::Multiply
                    && [(K::Angle, K::Length), (K::Length, K::Angle)].contains(&(left, right));
                assert_eq!(
                    operator.arc_length_hint(left, right),
                    hint,
                    "hint {left:?} {token} {right:?}"
                );
                if hint {
                    hints += 1;
                    assert!(actual.is_none());
                }
                if actual.is_some() {
                    accepted += 1;
                    if operator == B::Multiply {
                        products += 1;
                    }
                    if operator == B::Divide {
                        quotients += 1;
                    }
                }
            }
        }
    }
    assert_eq!(accepted, 71);
    assert_eq!(products, 17);
    assert_eq!(quotients, 14);
    assert_eq!(hints, 2);
}

#[test]
fn product_rows_and_operator_table_agree_with_the_actual_normative_chapter() {
    let source = include_str!("../../../docs/book/src/spec/formula-language/grammar.md");
    let start = source
        .find("| Left | Right | `*` gives | `/` gives |\n")
        .unwrap();
    let rows = source
        .get(start..)
        .unwrap()
        .lines()
        .skip(2)
        .take_while(|line| line.starts_with('|'))
        .map(|line| {
            line.split('|')
                .skip(1)
                .take(4)
                .map(|cell| cell.trim().trim_matches('`').to_owned())
                .collect::<Vec<_>>()
        })
        .collect::<Vec<_>>();
    let expected = PAIRS
        .into_iter()
        .map(|(left, right, product, quotient)| {
            vec![
                left.token().to_owned(),
                right.token().to_owned(),
                product.map_or("—", K::token).to_owned(),
                quotient.token().to_owned(),
            ]
        })
        .collect::<Vec<_>>();
    assert_eq!(rows, expected);
    let start = source
        .find("| Operator | Operands | Result | Refused when |\n")
        .unwrap();
    let rows = source
        .get(start..)
        .unwrap()
        .lines()
        .skip(2)
        .take_while(|line| line.starts_with('|'))
        .collect::<Vec<_>>();
    assert_eq!(rows,[
        "| `+` `-` | T, T | T | the two kinds differ |",
        "| `-` unary | N | N | the operand is a `count`, a `boolean`, a `point` or an `edge` |",
        "| `*` | a pair §5.1 lists | as listed | the pair is absent |",
        "| `/` | a pair §5.1 lists | as listed | the pair is absent, or the divisor is zero |",
        "| `^ 2` | length | area | another exponent |",
        "| `^ 2` | ratio | ratio | another exponent |",
        "| `^ 2` | count | count | another exponent |",
        "| `==` `!=` `<` `<=` `>` `>=` | T, T | boolean | the kinds differ, or the comparison chains |",
    ]);
    assert!(
        source.contains("An angle times a length is refused and the diagnostic names `arc_length`")
    );
}

#[test]
fn metadata_tokens_match_independent_existing_canonical_serialization() {
    use sc_core::recipe::FormulaExpression;
    for (operator, symbol) in OPERATORS {
        let source = format!("1 cm {symbol} 1 cm");
        let normalized = FormulaExpression::parse(&source)
            .unwrap()
            .normalize_literals()
            .unwrap();
        assert_eq!(
            normalized.canonical_form().as_str(),
            format!("({} length:10000 length:10000)", operator.token())
        );
    }
    for (operator, source) in [(U::Negate, "-1 cm"), (U::Square, "1 cm ^ 2")] {
        let normalized = FormulaExpression::parse(source)
            .unwrap()
            .normalize_literals()
            .unwrap();
        assert_eq!(
            normalized.canonical_form().as_str(),
            format!("({} length:10000)", operator.token())
        );
    }
}
